[package]
name = "ctfsak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
base64 = "0.13.0"
urlencoding = "2.1.0"
rsa = "0.5.0"
rand = "0.8.4"
sha2 = "0.9.8"
